name: 56Street
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#660315'
    - '#000000'
    - '#0b1e44'
    - '#070f25'
    - '#36020b'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
