name: 56Street
favicon: null
layout_spectrum: 0.59709
typography_spectrum: 0.9955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9b9aa0'
    - '#2f302b'
    - '#d9d9d9'
    - '#dab274'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.3729545185342431
  rhythmicContrast: 0.38374003022909164
purpose: []
