name: 56Street
favicon: null
layout_spectrum: 0.9382827742956579
typography_spectrum: 0.3849526233971119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8837578964885324
  lightness: 0.9973467919044197
  saturation: 0.3729545185342431
  rhythmicContrast: 0.38374003022909164
purpose: []
